name: Sonar
on:
  push:
    branches:
      - main

  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Install Sonar Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v6.0.0

      - name: Configure build
        run: "cmake -B build -Wno-dev -DCMAKE_BUILD_TYPE=Debug"

      - name: Build project
        run:  build-wrapper-linux-x86-64 --out-dir sonar-build-output cmake --build build
                
      - name: Run Sonar scanner
        uses: SonarSource/sonarqube-scan-action@v6.0.0  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}          
        with:
          args: >
            -Dsonar.cfamily.build-wrapper-output=sonar-build-output

